# permissions for end users to edit clusterdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterdomain-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openloft
    app.kubernetes.io/part-of: openloft
    app.kubernetes.io/managed-by: kustomize
  name: clusterdomain-editor-role
rules:
- apiGroups:
  - storage.openloft.cn
  resources:
  - clusterdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.openloft.cn
  resources:
  - clusterdomains/status
  verbs:
  - get
