apiVersion: storage.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: vcluster-isolated-template
spec:
  access:
    - users:
        - "*"
      verbs:
        - get
  description: This virtual cluster template deploys an isolated vcluster
  displayName: Virtual Cluster Template (Isolated)
  template:
    accessPoint:
      ingress: {}
    helmRelease:
      chart: {}
      values: |-
        # Below you can configure the virtual cluster
        isolation:
          enabled: true
          podSecurityStandard: privileged
          resourceQuota:
            enabled: true
            quota:
              requests.cpu: 10
              requests.memory: 20Gi
              requests.storage: "100Gi"
              requests.ephemeral-storage: 60Gi
              requests.nvidia.com/gpu: 16
              limits.nvidia.com/gpu: 16
              limits.cpu: 20
              limits.memory: 40Gi
              limits.ephemeral-storage: 160Gi
              services.nodeports: 0
              services.loadbalancers: 1
              count/endpoints: 40
              count/pods: 20
              count/services: 20
              count/secrets: 100
              count/configmaps: 100
              count/persistentvolumeclaims: 20
            scopeSelector:
              matchExpressions:
            scopes:

        sync:
          nodes:
            enabled: false

          ingresses:
            enabled: true

        vcluster:
          image: rancher/k3s:v1.25.14-k3s1

        coredns:
          enabled: true

        ingress:
          enabled: true

        # Checkout https://vcluster.com/pro/docs/ for more config options
    instanceTemplate:
      metadata: {}
    metadata: {}
    spaceTemplate:
      metadata: {}
